name: Registry Management

on:
  repository_dispatch:
    types:
      - registry-update

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  registry-management:
    runs-on: ubuntu-latest
    steps:
      - name: Manage Registry
        uses: paperback-community/registry-manager@stable
        with:
          github-token: ${{ secrets.REGISTRY_MANAGER }}
          repository: ${{ github.event.client_payload.repository }}
          branch: ${{ github.event.client_payload.branch }}
